build-osx:
  stage: build
  tags:
    - darwin
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - fbs freeze --debug
    - fbs installer
  only:
    - master
  artifacts:
    expose_as: 'build_darwin'
    paths: ['target/Lambent4Qt.dmg']

build-win:
  stage: build
  tags:
    - windows
  script:
    # for starters: choco install vcbuildtools, vcredist2010,vcredist2012 -x86 add C:\Windows\SysWOW64\ to windows path and reboot
    # and then choco install python3 --version=3.6.8
    # and choco install git --params "/GitAndUnixToolsOnPath"
    - C:\Python36\python.exe -m venv venv
    - $env:Path += ";C:\Windows\System32\downlevel"
    - .\venv\Scripts\activate.bat
    - pip install --upgrade pip wheel --user
    - pip install -r requirements.txt --user
    - fbs freeze --debug
    - fbs installer
    - dir target
    
  only:
    - master

