build-osx:
  stage: build
  tags:
    - darwin
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - fbs freeze --debug
    - fbs installer
  only:
    - master
  artifacts:
    expose_as: 'build_darwin'
    paths: ['target/Lambent4Qt.dmg']

build-win:
  stage: build
  tags:
    - windows
  script:
    # for starters: choco install vcbuildtools python3 pip
    # and choco install git --params "/GitAndUnixToolsOnPath"
    - py.exe -m venv venv
    - .\venv\Scripts\activate.bat
    - pip install --upgrade pip wheel
    - pip install -r requirements.txt
    - fbs freeze --debug
    - fbs installer
    - dir target
    
  only:
    - master

